version: '3.8'

services:
  backend:
    image: akhmadzaqiriyadi/stmadb-portal-be:latest # Ganti dengan username Docker Hub Anda
    build:
      context: ./stmadb-portal-be
      dockerfile: Dockerfile
    container_name: stmadb_be
    ports:
      - "8000:8000" # Map port 8000 host ke 8000 container
    env_file:
      - ./stmadb-portal-be/.env # Path ke file .env backend
    restart: unless-stopped
    networks:
      - stmadb-net

  frontend:
    image: akhmadzaqiriyadi/stmadb-portal-be:latest # Ganti dengan username Docker Hub Anda
    build:
      context: ./stmadb-portal-fe
      dockerfile: Dockerfile
    container_name: stmadb_fe
    ports:
      - "3000:3000" # Map port 3000 host ke 3000 container
    env_file:
      - ./stmadb-portal-fe/.env # Path ke file .env frontend
    restart: unless-stopped
    networks:
      - stmadb-net

networks:
  stmadb-net:
    driver: bridge