name: Build and Deploy STMADB Portal

on:
  push:
    branches:
      - main # Hanya berjalan saat ada push ke branch main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./stmadb-portal-be
          file: ./stmadb-portal-be/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stmadb-portal-be:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./stmadb-portal-fe
          file: ./stmadb-portal-fe/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/stmadb-portal-fe:latest

  deploy:
    needs: build-and-push # Jalankan job ini setelah build-and-push selesai
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # 1. Login ke Docker Hub di server Anda
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            # 2. Pindah ke direktori proyek
            cd ~/stmadb-portal 
            
            # 3. Ambil perubahan terbaru dari Git (termasuk docker-compose.yml)
            git pull

            # 4. Jalankan ulang. Docker-compose akan otomatis pull image baru.
            docker-compose up -d --remove-orphans

            # 5. Bersihkan image lama
            docker image prune -f